### ISSUE TITLE
Docker server image broken

### ISSUE THREAD

**Issue by jblakley** [IntelLabs/vdms#125]
The intellabs/vdms:server docker image no longer works. The problem seems to be that the program "/vdms/vdms" as expected by "/start.sh" does not exist in the image anymore.

When running kubernetes with intelllabs/vdms:server, log yields:
/start.sh: line 3:     8 Illegal instruction     (core dumped) vdms

Inspecting via docker run -it intellabs/vdms:server bash reveais contents of /vdms to be only:
config-vdms.json

The executable "vdms" exists only in /usr/local/bin

Same results when building server image from intellabs/vdms:base. Have not tried building the base image from scratch.

**Comment by jblakley** [comment]
The issue has reappeared in latest docker images. intellabs/vdms:latest and intellabs/vdms:server

**Comment by luisremis** [comment]
I am looking into this now.

**Comment by luisremis** [comment]
I have just updated the docker images and seems to be working correctly. Not exactly sure what happened but images should be up and running now. Please let me know if you are still having issues.

**Comment by luisremis** [comment]
Should be solved in #127, let me know if you are still having issues.

**Comment by jblakley** [comment]
Just did pull on intellabs/vdms:base and intellabs/vdms:server -- both seem to still be missing /vdms/vdms

**Comment by luisremis** [comment]
There should be no /vdms/vdms. 
The new docker images install vdms binary on /usr/local/bin.

/vdms should only contain a config file, and the vdms server can be started from /vdms to use that path. 

Is the image not working for you?

**Comment by jblakley** [comment]
Still same issue. Dockerfile for intellabs/vdms:server is consistent with need to have /vdms/vdms: 
 `  
# Pull base image.
FROM intellabs/vdms:base

# Setup entry point

RUN echo '#!/bin/bash' > /start.sh && \
    echo 'export LD_LIBRARY_PATH=/vdms/utils:/pmgd/lib:$(find /usr/local/lib/ / -type f -name "*.so" | xargs dirname | sort | uniq | tr "\n" ":")' >> /start.sh && \
    echo 'cd /vdms' >> /start.sh && \
    echo 'rm -rf db' >> /start.sh && \
    echo './vdms' >> /start.sh && \
    chmod 755 /start.sh

EXPOSE 55555
CMD ["/start.sh"]`

**Comment by jblakley** [comment]
Just checked the actual intellabs/vdms:server image and start.sh has "vdms" not "./vdms.sh".

**Comment by luisremis** [comment]
Oh I see, you were probably looking into the develop branch without the patch. We have recently merged the fix of the docker files, now it should be good:
https://github.com/IntelLabs/vdms/blob/develop/docker/server/Dockerfile

The docker image should be up to date and ready to pull. Let us know if you are still having issues, if not, we can close this issue.
