### ISSUE TITLE
Cloud Storage Integeration of VDMS through TileDB configuration 

### ISSUE THREAD

**Issue by vinothalagupandi** [IntelLabs/vdms#145]
What is the procedure to store the Tile DB artefacts such as Images , Entity, Descriptors, Videos to Cloud Storage services by configuring TileDB

**Comment by Ragaad** [comment]
For descriptors you have to create a descriptor set with either ["TileDBDense", "TileDBSparse"] engine. then it will add any descriptor to the new set . for Images, you need to make sure the format flag of the AddImage is "tdb" in the case it will store the image in the Tiledb format. We do not support Tiledb Video yet, but we are open to do so, for entities all entities are stored in our graph database PMGD.

**Comment by vinothalagupandi** [comment]
Thanks for the reply but my request is how to store the entire “db” folder  to cloud storage such as azure blob/s3/gcp instead of storing in local file systems (/db/images/jpg) is there any way to change it via vdms or tile db configuration?

**Comment by Ragaad** [comment]
We did some prototypes where we store the image/video to s3 bucket. it is not in the release yet, but if this match your request let us know, we could consider releasing it?

**Comment by vinothalagupandi** [comment]
Yeah Storing all vdms data in s3 kinda storage is my exact request.Can you share this ? Thanks

**Comment by Ragaad** [comment]
the code is quite old now, we will update it and integrate it with the newest VDMS API and release it with the coming release. If you need to see the old code, it is in our open-source project VCL. Agian, this is not integrated yet with the newest VDMS code. 

https://github.com/IntelLabs/vcl/blob/feature_dfs/src/RemoteConnection.cc

**Comment by ifadams** [comment]
@cwlacewe closing as stale, though did this get resolved through revival of S3 connector integration? @rolandoquesada?
