### ISSUE TITLE
_date on properties not working correctly.

### ISSUE THREAD

**Issue by luisremis** [IntelLabs/vdms#16]
The following query follows the API and because of the _date is not working.
Make sure this is working and fully supported. 

query = """
[
   {
      "AddEntity" : {
         "class" : "doctor",
         "properties": {
             "name": "Mark",
             "age": 5, 
             "speciality": "brains", 
             "dob": {"_date", "Sat Nov 1 18:59:24 PDT 1930"}
         }
      }
   }
]   
"""

**Comment by vishakha041** [comment]
Aside from the doctor being 5 year old which is worrisome, I am not sure I follow the problem :)

**Comment by luisremis** [comment]
He even took a gap year. 
Error message is returned even if this is matching the API specification.

**Comment by vishakha041** [comment]
This is what our JSON spec accepts:
"dob": {"_date", "Sat Nov 1 18:59:24 PDT 1930"}  ==> 
"dob": {"_date" : "Sat Nov 1 18:59:24 PDT 1930"}
I don't know which part you want to change that but the current query you are trying doesn't fit in the spec.

**Comment by luisremis** [comment]
Gosh you are right, my bad.
