### ISSUE TITLE
How to perform an image classification task using vdms?

### ISSUE THREAD

**Issue by onefanwu** [IntelLabs/vdms#166]
Hi vdms team,
How to perform an image classification task using vdms? Suppose a PyTorch model is used for prediction.

Best regards,
Yifan Wu

**Comment by ifadams** [comment]
@onefanwu Currently we do not explicitly support inference as a native API call, however you may want to take a look at the use-defined functions as a path here. 

@rv355 can chime in with more details here.

**Comment by ifadams** [comment]
cc @cwlacewe closing as a question is (sort of) resolved.

**Comment by onefanwu** [comment]
Thanks for your helpful reply.
