### ISSUE TITLE
vdms[7483] trap invalid opcode ip:7477432f3857 sp:7ffcafb6c820 error:0 in libtiledb.so.2.14[74774306b000+9e5000]

### ISSUE THREAD

**Issue by ionutnechita-intel** [IntelLabs/vdms#171]
Hello VDMS Team,

I notice this today:
```
[  198.644340] traps: vdms[7483] trap invalid opcode ip:7477432f3857 sp:7ffcafb6c820 error:0 in libtiledb.so.2.14[74774306b000+9e5000]
```

I use default Docker image: intellabs/vdms:latest

My CPU: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz

Strace file:
[strace-vdms-core-dump.txt](https://github.com/user-attachments/files/15593844/strace-vdms-core-dump.txt)

**Comment by ifadams** [comment]
@cwlacewe who is in charge of TileDB at this point? 

@ionutnechita-intel can you provide more context about your setup and how to reproduce this bug? i.e. what commands were issued, which client (python vs cpp) etc?

**Comment by ifadams** [comment]
@cwlacewe I haven't heard any response nor enough context to reproduce. Closing this issue as stale for the moment.
