### ISSUE TITLE
results not working on FindImage

### ISSUE THREAD

**Issue by luisremis** [IntelLabs/vdms#19]
This query will not show properties of the images when using the results block:

query = """
[
   {
      "FindEntity" : {
         "class" : "patient",
         "_ref" : 43,
         "constraints" : { "age_at_initial" : [ ">", 80 ] }
      }
   },
   {
      "FindEntity" : {
         "class" : "Scan",
         "_ref" : 555,
         "link" : { "ref" : 43 }
      }
   },
   {
      "FindImage" : {
         "link" : { "ref" : 555 },
         "operations": [
             {
                 "type": "resize",
                 "height": 100,
                 "width": 100
             }
         ], 
         "constraints": {
             "number": [">=", 85, "<=", 90]
         }, 
         "results": {
             "list": ["name"]
         }
         
     }
   }
]

**Comment by vishakha041** [comment]
Do you have the graph you tested this on if I want to repeat it.

**Comment by luisremis** [comment]
Fixed in #35
