### ISSUE TITLE
AddImage using existing blobs

### ISSUE THREAD

**Issue by vishakha041** [IntelLabs/vdms#27]
Current version of AddImage expects blobs of image to be provided. It would be good to do a FindImage and use the result of that as the blob for AddImage.

**Comment by ifadams** [comment]
@cwlacewe Lets revisit this. This isn't a bad idea, but nobody is asking for it as of yet.

**Comment by ifadams** [comment]
Superseding ticket: https://github.com/IntelLabs/vdms/issues/200
