### ISSUE TITLE
AddImage doesn't allow conditional adding

### ISSUE THREAD

**Issue by vishakha041** [IntelLabs/vdms#28]
From the implementation that's in develop right now, it seems like there is no conditional add version for AddImage. Is that deliberate or bug?

**Comment by luisremis** [comment]
Not deliberate, not a bug. Just "Not Implemented"

**Comment by vishakha041** [comment]
Is this implemented now?

**Comment by ifadams** [comment]
@cwlacewe not relevant for the time being.
