### ISSUE TITLE
Client Library Blob bug

### ISSUE THREAD

**Issue by luisremis** [IntelLabs/vdms#31]
VDMSClient.query(2) has a bug in the implementation, that will not copy the blobs into the protobuf query. 
We need to add the correct copy. 
We should also consider creating a Query object, with an std::string* add_blob() method so that we avoid coping the content of the blobs that are provided by que client.

**Comment by luisremis** [comment]
Fixed by #32

**Comment by Ragaad** [comment]
The current fix is performing as expected
