### ISSUE TITLE
Retry transactions on lock timeouts

### ISSUE THREAD

**Issue by vishakha041** [IntelLabs/vdms#51]
Once the PMGD concurrency branch is merged and we remove locks from PMGDQueryHandler, there might be some failed transactions due to lock timeout. It might be worth figuring out a way to retry them since there was no user error there.

**Comment by ifadams** [comment]
@cwlacewe this is a well known issue at this point, closing for the moment, though we should probably revisit it as this becomes a serious problem under heavy load/high concurrency.
