### ISSUE TITLE
Create a distribution package for the Python code

### ISSUE THREAD

**Issue by mihaic** [IntelLabs/vdms#6]
This will make it easier to install VDMS; specifically, it will remove the need to manipulate `PYTHONPATH`.
https://packaging.python.org/tutorials/distributing-packages/

Bonus: add it to PyPI.

**Comment by luisremis** [comment]
Great, thanks for the suggestion. 

At the moment, we offer the Python client version as stand-alone, that can be downloaded from:
https://github.com/IntelLabs/vdms/releases/download/v1.0.0/vdms-python-client-v1.0.0.tgz 
But there is still the need to manipulate PYTHONPATH, as you pointed out. 

I will look into this.

**Comment by luisremis** [comment]
Done, thanks for the suggestion!
