### ISSUE TITLE
Ability to delete entities

### ISSUE THREAD

**Issue by mwahle** [IntelLabs/vdms#60]
We would like to be able to run the very basic operation of deleting entities, for example like so:
```
db.query([{"DeleteEntity": {'class': 'Test', 'constraints': {'x': ['==', 2]}}}])
```

**Comment by luisremis** [comment]
Thanks for this suggestion. We recognize that Deleting is something useful to have for many applications, and that this functionality will have to be included at some point. 
However, we decided to give priority of Add/Update of new entities (Feature Vectors, Videos) kind of operations and other features before we start including Delete operations. 
Please let us know if you consider Delete operations to be of urgent need and so we can take this into consideration.

**Comment by LiberiFatali** [comment]
Yes, this is really useful. It would be great if we can delete the image, descriptor, descriptor set. We're looking forward to this feature.

Thank you!

**Comment by ifadams** [comment]
@cwlacewe theoretically we have basic deletion capabilities (see https://github.com/IntelLabs/vdms/wiki/Deletion-Capabilities) so closing for the time being.
