### ISSUE TITLE
Strategic improvement: directly integrate with other systems (for example a PACS)

### ISSUE THREAD

**Issue by mwahle** [IntelLabs/vdms#67]
It would be of immense value if VDMS could directly integrate with other systems. This way, instead of having some sort of external process that crawls over a system or its backend and retrieves images and the associated data, VDMS could directly be populated from within a PACS system (for example).

This way the external system could keep VDMS up to date in a real-time fashion, opening the door for so many possibilities. One could also generate events from within VDMS to notify listeners.... ah, from here one can really go and dream about applications.

However simply having data pushed into VDMS fast and efficiently is already an enormous value proposition.

**Comment by ifadams** [comment]
@cwlacewe closing, not relevant in our current era.
