### ISSUE TITLE
Strategic improvement: VDMS SDK or Plugin API

### ISSUE THREAD

**Issue by mwahle** [IntelLabs/vdms#68]
For example, users could be able to develop their own image transformation plugins and share them over a central VDMS project website... also opens a door for a dual open/closed-source business model...

**Comment by luisremis** [comment]
This is a great and valuable suggestion. We have been thinking of ways of adding User-defined transformations but did not have the time/resources to turn these ideas into a features. We hope that the community at some point will pick on our efforts and helps us.

**Comment by ifadams** [comment]
@cwlacewe 

@rv355 UDFs partially address this at this point. Closing.
