### ISSUE TITLE
Add docstrings to Python code

### ISSUE THREAD

**Issue by mihaic** [IntelLabs/vdms#7]
They are very helpful for interactive use.

You can also use them to generate HTML documentation automatically with `sphinx-apidoc`:
http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html

**Comment by ifadams** [comment]
While this is a reasonable ask, we should consider it more as an ongoing maintenance task/revisit given age of ticket. Closing for now. @cwlacewe
