### ISSUE TITLE
Link entities from result sets

### ISSUE THREAD

**Issue by mwahle** [IntelLabs/vdms#70]
Currently, when there are multiple FindEntitiy blocks, one gets multiple result sets where the entities are not linked to each other, even when there were refs between the FindEntity blocks.

This makes interpreting results difficult, requires multiple query rounds, or requires workarounds in the schema design, all of which are not desirable.

Please add a mechanism that directly shows the links between entities from different FindEntity blocks.

**Comment by luisremis** [comment]
I see. Let me understand this right. 

If you do a findEntity with a "_ref" and get, say 2 results (a and b), and if you use that reference and do another find*, and get 4 results (x, y, z, w), you would like to be able to tell which of those 4 are linked to which of the 2 on the first find* (say, a linked to x and y, and b linked to z and w). 
Is this right?

**Comment by mwahle** [comment]
This is exactly right.

**Comment by ifadams** [comment]
@cwlacewe I see what they're talking about, but unclear if this is even something desired at this point, and may be complicated to implement.
